# Generated by Django 3.2 on 2021-05-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judulbuku', models.CharField(max_length=240, verbose_name='Judul Buku')),
                ('kategori', models.CharField(max_length=240, verbose_name='Kategori')),
                ('penerbit', models.CharField(max_length=240, verbose_name='Penerbit')),
                ('pengarang', models.CharField(max_length=240, verbose_name='Pengarang')),
                ('lokasirak', models.CharField(max_length=240, verbose_name='Lokasi Rak')),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
        ),
        migrations.CreateModel(
            name='Kategoribuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=240, verbose_name='kategori')),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namapelanggan', models.CharField(max_length=240, verbose_name='Nama Pelanggan')),
                ('email', models.EmailField(max_length=254)),
                ('alamat', models.CharField(max_length=240, verbose_name='Alamat')),
                ('telepon', models.CharField(max_length=20, verbose_name='Telepon')),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggalpinjam', models.DateTimeField(verbose_name='Tanggal Pinjam')),
                ('tanggalpengembalian', models.DateTimeField(verbose_name='Sale End Time')),
                ('id_buku', models.IntegerField(verbose_name='id_buku')),
                ('id_user', models.IntegerField(verbose_name='id_user')),
                ('id_pelanggan', models.IntegerField(verbose_name='id_pelanggan')),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=240, verbose_name='User Name')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
        ),
    ]
