# Generated by Django 3.2 on 2021-05-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpusapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggalpengembalian',
            field=models.DateField(verbose_name='tanggalpengembalian'),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggalpinjam',
            field=models.DateField(verbose_name='tanggalpinjam'),
        ),
    ]
